---

name: Main

on: [push]

jobs:

  build_n_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build project
        run: dotnet build

      - name: Test project
        run: dotnet test
